package errors;

public enum ErrorType {
    LEXICAL_UNKNOWN_CHARACTER,
    LEXICAL_UNTERMINATED_STRING,
    LEXICAL_INVALID_NUMBER,
    
    SYNTAX_UNEXPECTED_TOKEN,
    SYNTAX_MISSING_TOKEN,
    SYNTAX_INVALID_STRUCTURE,
    SYNTAX_MISSING_SEMICOLON,
    
    SEMANTIC_UNDECLARED_VARIABLE,
    SEMANTIC_TYPE_MISMATCH,
    SEMANTIC_UNDECLARED_FUNCTION,
    SEMANTIC_ARGUMENT_COUNT_MISMATCH,
    SEMANTIC_UNDECLARED_EVENT,
    SEMANTIC_UNDECLARED_AGENT,
    SEMANTIC_EVENT_PARAMETER_MISMATCH,
    SEMANTIC_LOG_VARIABLE_NOT_IN_SCOPE,
    SEMANTIC_CALL_ARGUMENT_MISMATCH,
    SEMANTIC_DUPLICATE_DECLARATION,
    
    RUNTIME_DIVISION_BY_ZERO,
    RUNTIME_VARIABLE_NOT_FOUND,
    RUNTIME_AGENT_NOT_FOUND,
    RUNTIME_TYPE_ERROR,
    RUNTIME_STACK_OVERFLOW
}